apiVersion: v1
kind: Namespace
metadata:
 name: dev
---
# 定义PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc001
  namespace: dev
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

